language: python
env:
  global:
  - JEKYLL_ENV=production
  - PLACE=za-wc013
  - secure: LIzVWVULKxZScFbXC43snoPysNFxXnNVYiq7tM5qlcWoJtXxqd0AAiSIfp0yZQPYeYailEPXmvVzknfDvg8+JtyiVZ9DXxNSDRsPS2+jwJnY9mjJMlJu5D4h6eV104MsPDg+KeVNjUqxKgwZkRELe3L1I/Y6NWrfZ119XmDyTitHFWZKUCAOoGHyoDciV5W8H07UPPeQR9QZA/emRtRQbpz3V96UqKnXg5OzGvdhLLNX0a+mNSPYxaEz9IHA+FLkFyH+UXvvYU7WZs8GQVYDoU9WGn6hmpaHiweX2C1fSudlXAIotcoR4xdjdpGPjTzrKOYyu95Sl80AyFOekDiaIzPenlifeYe0b1bAxhp39NAuLB8DRFA4/c9WVo69NUZaJlJL7r/Ir6UQzBXkMpQsdpD5ZLq3ydci2zcY8miUlRriPP7SFZ7hUfFVsqbfAjAi3nNMi/LHxvtm+POf0+X13tXIk9D8jYSQqeK9BTkEBiFQfGVv4HWuUydJ/JQIXgyMzwE2nDLNLHFDyRUQbKBA5xsgcsd7Q+eqUWOz0uql/ZkXti2ZIomXS7wNzjeG0o9yhyVK2ik1Y66pWyaV8QAR8Vb8hkXtAH9SDBOMBMHaeZW8dqT6ucR+AmpLCU148r5nud2KjXEOdbq2kRSLg20JolVDfftCyZAGugIQxetF3QQ=
  - secure: Ho1Rosz5QftuQ2kzIYjUtm5tj138tWn9Xk5hn7IJ3IyZ0qEifZ6NC9+L+W/90rI0LAB5IGuttTbO8hyaJx4FKo4uVtJLP3jLyOJbtAT7+2q6EZ70IcVqAvm9llxDAtaIeQ/7+Qaq9BXj6h5Kj3nF3WQ+uNT+NtjOmPfgyvST4saSuHWPr7f4ILKy5t9tIo4v2Bkekenm1kzpdBA+5WQQ6mSj+IiykVdo7dyqdwydoAQkfp9htdCZwDB3NuDV4JJi2W7VdI+BJnHQRtezTzzsMJN4A/AiqW9ijxgcwFF7G6siFOuuoNNJ8Yg6OIPq2GHju67M89qm7ckIpVw5KoIgvO/7IhP4RW1+J2c1towxhye6+1Eq7geb86KlxtVa6ktnwNvmV82JtWujkmYBZGewGjCc1HgTAarie6z2OXJ6BbnGulBufFuHbdQ60RDvBUTctcioV8K4lGZRdtp1X6l6GyagMKwtbvKaVuakFjiAFS6BjP6DB6mozeMvpJpf9AgV3iLeSlFHaais/6Yq1kg8GRV1YJbthA4QBlN10mCY515tkkldx1Vg9I/8c6/YE92ZV5zmqjb7BXIR/HV6eY5Ua0TYGQL0y9ci5zjkLwLLfa9gHHDMMH4lxlJDE6BQ7o6BBHeZabipu9e/KGVlg7L/i/xVBZRrYLJE/UBkrvkB1z4=
install:
- git clone --depth 1 https://github.com/laws-africa/openbylaws-microsite.git build
- cd build
- pip install -r requirements.txt
- bundle install
- python bin/place.py $PLACE
script: bundle exec jekyll build --trace
deploy:
  provider: pages
  local_dir: build/_site
  target_branch: gh-pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: bergrivier.openbylaws.org.za
  on:
    branch: master
